#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")"

# Use :contrib alias only when not --lang
if echo "$@" | grep -q -- "--lang"; then
  exec clojure -M -m parity.core "$@"
else
  exec clojure -M:contrib -m parity.core "$@"
fi
