#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")"

# Use :contrib alias only when not --lang
if echo "$@" | grep -q -- "--lang"; then
  exec clojure -M src/parity/core.clj "$@"
else
  exec clojure -M:contrib src/parity/core.clj "$@"
fi
